You are approached by both Kuon and Mateo. The latter attempts to speak a few times, with each ending in him either shaking his head or looking to Kuon. Finally, Kuon sees that this is going nowhere and speaks up. “Listen, I've been talking with Mateo here and he says that if he makes some modifications to my cybernetics I could do my job more effectively. I'm for it, but I figured I should get your input.” You ask Mateo what he thinks of this. He lets out an exasperated sigh, “Well Daisy Bell, he ain't lying. If I tweaked some things here and there I could essentially overclock his cybernetics. Thing is, if I do that it would considerably increase the metabolic conversion rate.” He looks right at Kuon as he says this, and is greeted only by a blank stare in response. “Riiiight… it would mean that you'd have to eat more to compensate for the extra oomph.” You can almost make out the spark of realization in Kuon's eyes as he is told this. They both look towards you, after all, it's ultimately your decision to make.
+[Approve Overclocking]->Overclock
+[Deny Overclocking]->Deny

== Overclock ==
You approve the procedure. Without skipping a beat, Kuon basically drags Mateo back to the workshop. It takes a few hours, but Kuon emerges looking no worse for wear. Mateo follows suit and you overhear snippets of their conversation, “Now something you might have to watch out for is heat buildup, but it should be manageable with some ice. Other than that, what is the first thing you're gonna do now that you're overclocked?” Kuon takes a brief moment to ponder the possibilities before responding, “Find something to eat.”
->DONE
== Deny ==
You inform Kuon that there is no need to improve his effectiveness. He is doing a good job as is, and you don't want him overworking himself. He seems disappointed but understands where you're coming from. “Very well, I respect your decision. I'll be leaving then.” Mateo tags along with him, and you catch him turn back towards you and mouth the words “Thank you”.
->DONE