Your ship descends past the wispy clouds, the surface of the planet coming into view. A wasteland devoid of vegetation. Instead, great metal structures jut awkwardly from the ground at a horrid mish-mash of angles. These are strewn about the landscape in strange clusters. While most of your crew questions what purpose these structures might have had, Mateo promptly informs everyone that what they’re looking at is only a small part of a possibly greater whole. When pressed further on what he meant, Mateo's only answer was “Beats me” accompanied by a sly smirk.
When you finally land, no more than a few moments pass before a communication line has been opened between your crew and the archaeologists present at the dig site. They explain that Kellis has been paying them to essentially wander the planet and report any interesting finds they happen upon while digging. They then ask if you would be willing to give them some supplies for their next dig, as Kellis has deemed such expenses non-essential. They promise that you will be compensated if you choose to do, but that they understand should you be reluctant to do so.
+[Donate Supplies] -> Donate
+[Decline] -> Decline
== Donate ==
After a brief period of seemingly stunned silence, the lead archaeologist manages to speak. “We are eternally grateful for your contribution. Honestly, we didn't expect such generosity from a robot.” They chuckle softly to themselves before their eyes go wide. “No offense meant of course... I hope that comment doesn’t change your mind.” You explain that whether or not you could be offended is irrelevant. So long as they are still willing to pay you'll make sure they get the supplies they need
->DONE
== Decline ==
You inform the archaeologists that while unfortunate, their shortage of supplies is not your primary responsibility. They are visibly disheartened, and the lead archaeologist finally speaks. “What you said is true, but we figured it couldn't hurt to ask right?” You correct them, saying that had they not asked in the first place they wouldn't have left themselves open to disappointment. Following an awkward silence, the lead archaeologist concedes, “I suppose that's true as well…” You depart before they can ask for anything else.
->DONE