The recent leg of your journey has been quite peaceful, unfortunately this soon changes. “What the hell is that?!” Cries a crew member as he looks out of the observatory window. Soon a small crowd has gathered, all clamoring to see what's causing the ruckus. You take a look through the external cameras and are at a loss for words. Ahead of the ship lies a peculiar sphere emitting a dull pink glow, the space around it seems to be distorted, corrupted even. This “corruption” seems to be spreading, and as you look on it becomes apparent that it's drawing closer to the ship.
+[Flee from the Energy]->Flee
+[Brace for Impact]->Brace

== Brace ==
From the sphere erupts a pulse of soft pink light. The wave washes over the ship, damaging equipment and fracturing the hull. Additionally, a neon fissure appears upon the main deck. It emits a similar light to the sphere, but that's not all. Crew members report hearing faint traces of...music? When asked to describe the composition most simply respond with some variant of “The beats are chill”. You see no issue in allowing the crew access to the anomaly, and their mood seems to improve after listening to whatever's emanating from the fissure.
->DONE
== Flee ==
You order the ship to retreat. As you draw farther away the crew breathes a sigh of relief, but this moment of respite is short-lived. A tendril of corruption bursts forth from the sphere, careening towards your ship. It passes through all barriers and makes contact with a few unfortunate souls. Once they are completely engulfed their bodies begin to break apart, and from the cracks spring forth streaks of bright pink. In a blinding flash the affected crew members break apart into little more than pixelated dust. Thankfully, it seems the corruption can no longer reach you. You forge ahead.
->DONE