name: Build

on: [push, pull_request]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - SpaceUber
        unityVersion:
          - 2019.4.8f1
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
          #- WebGL # WebGL.
    steps:
      - uses: actions/checkout@v2.3.2
        with:
          lfs: true
      - uses: actions/cache@v2.1.1
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      - uses: game-ci/unity-builder@v2.0-alpha-6
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: A Cog in the Cosmic Machine-${{ matrix.targetPlatform }}
          versioning: None
          customParameters: -CompressWithLz4HC
      - uses: actions/upload-artifact@v2.1.4
        with:
          name: Build
          path: build
  deploy:
    needs: build
    name: Deployment for ${{ build.strategy.matrix.targetPlatform }} on version ${{ build.strategy.matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: josephbmanley/butler-publish-itchio-action@v1.0.2
        if: github.base_ref == 'steven-deployment-fix' #&& github.event.pull_request.merged == true
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: ${{ build.strategy.matrix.targetPlatform }}
          ITCH_GAME: a-cog-in-the-cosmic-machine-dev-build
          ITCH_USER: nightangel47
          PACKAGE: build/${{ build.strategy.matrix.targetPlatform }}
      - uses: josephbmanley/butler-publish-itchio-action@v1.0.2
        if: github.base_ref == 'development' && github.event.pull_request.merged == true
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: ${{ build.strategy.matrix.targetPlatform }}
          ITCH_GAME: a-cog-in-the-cosmic-machine-dev
          ITCH_USER: partyparrotpatrolparade
          PACKAGE: build/${{ build.strategy.matrix.targetPlatform }}
      - uses: josephbmanley/butler-publish-itchio-action@v1.0.2
        if: github.base_ref == 'master' && github.event.pull_request.merged == true
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: ${{ build.strategy.matrix.targetPlatform }}
          ITCH_GAME: a-cog-in-the-cosmic-machine
          ITCH_USER: partyparrotpatrolparade
          PACKAGE: build/${{ build.strategy.matrix.targetPlatform }}
